<?xml version="1.0" ?>

<robot name="$(arg roboname)" xmlns:xacro="http://www.ros.org/wiki/xacro">
  
  <xacro:property name="PI" value="3.1415926835897931"/>
  <xacro:property name="base_height" value="0.4"/>
  <xacro:property name="tyre_y" value="0.855"/>
  <xacro:property name="tyre_length" value="0.225"/>
  <xacro:property name="tyre_radius" value="0.362"/>
  <xacro:property name="str_length" value="0.01"/>
  <xacro:property name="str_radius" value="0.1"/>
  <xacro:property name="str_angle" value="0.6"/>
  <xacro:property name="wheelbase" value="3.665"/>
  <xacro:property name="car_length" value="6.11"/>
  <xacro:property name="car_height" value="2.04"/>
  <xacro:property name="car_width" value="2.632"/>

  <xacro:property name="tyre_origin">
	    <origin xyz="0 0 0" rpy="${PI/2} 0 0"/>
  </xacro:property>
  <xacro:property name="tyre_origin_2">
      <origin xyz="0 0 0" rpy="0 0 ${PI/2}"/>
  </xacro:property>
  <xacro:property name="tyre_origin_3">
      <origin xyz="0 0 0" rpy="0 0 ${-PI/2}"/>
  </xacro:property>
  
	<xacro:include filename="$(find weichai_sim)/urdf/weichai_sim.gazebo"/>

<!--Car Body-->
<link name="base_link">
     <inertial>
        <origin xyz="${wheelbase/2} 0 ${base_height}" rpy="0 0 0"/>
        <mass value="3000.000000"/>
        <inertia ixx="480" ixy="0.000000" ixz="0.000000" iyy="1370" iyz="0.000000" izz="1370"/>
      </inertial>

     <visual>
        <origin xyz="0 0 -0.362" rpy="0 0 ${PI/2}"/>  
        <geometry>
          <mesh filename="package://weichai_sim/meshes/body.dae"/>
        </geometry>
     </visual>

      <collision name="chassis_collision">
        <origin xyz="0 0 -0.362" rpy="0 0 ${PI/2}"/>
        <geometry>
          <mesh filename="package://weichai_sim/meshes/body_collision.stl"/>
        </geometry>
      </collision>
</link>

<!--Right Steering-->
<link name="front_right_steering_link">
  <inertial>
    <origin xyz="0 0 0" rpy="0 0 0"/>
    <mass value="1.00"/>
    <inertia
          ixx="0.4"  ixy="0.000000"  ixz="0.000000"
          iyy="0.6"  iyz="0.000000"
          izz="0.4"/>
  </inertial>
</link>

<!--Left Steering-->
<link name="front_left_steering_link">
      <inertial>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <mass value="1.00"/>
        <inertia
          ixx="0.4"  ixy="0.000000"  ixz="0.000000"
          iyy="0.6"  iyz="0.000000"
          izz="0.4"/>
      </inertial>
</link>

<!--Front Right Wheel-->
<link name="front_right_wheel_link">
      <inertial>
        <origin xyz="0 0 0" rpy="0 ${PI} 0"/>
        <mass value="10.00"/>
        <inertia
          ixx="0.4"  ixy="0.000000"  ixz="0.000000"
          iyy="0.6"  iyz="0.000000"
          izz="0.4"/>
      </inertial>

     <visual>
      <origin xyz="0 0 0" rpy="0 ${PI/2} 0"/>
        <geometry>
          <mesh filename="package://weichai_sim/meshes/ford_escape_wheel.dae"/>
        <scale xyz="1.2 1 1"/>
       </geometry>  
      </visual>

     <collision>
        <origin xyz="0 0 0" rpy="0 ${PI} 0"/>
        <geometry>
          <cylinder length="${tyre_length}" radius="${tyre_radius}"/>
	      </geometry>
     </collision>

</link>

<!--Front Left Wheel-->
<link name="front_left_wheel_link">
      <inertial>
        <origin xyz="0 0 0" rpy="0 ${-PI} 0"/>
        <mass value="10.00"/>
        <inertia
          ixx="0.4"  ixy="0.000000"  ixz="0.000000"
          iyy="0.6"  iyz="0.000000"
          izz="0.4"/>
      </inertial>

     <visual>
      <origin xyz="0 0 0" rpy="0 ${PI/2} 0"/>
       <geometry>
          <mesh filename="package://weichai_sim/meshes/ford_escape_wheel.dae"/>
            <scale xyz="1.2 1 1"/>
       </geometry>
      </visual>

      <collision>     
	      <origin xyz="0 0 0" rpy="0 ${-PI} 0"/>
        <geometry>
         <cylinder length="${tyre_length}" radius="${tyre_radius}"/>
        </geometry>
     </collision>
</link>

<!--Back Right Wheel-->
<link name="back_right_wheel_link">
      <inertial>
        <origin xyz="0 0 0" rpy="0 ${PI} 0"/>
        <mass value="10.00"/>
        <inertia
          ixx="0.4"  ixy="0.000000"  ixz="0.000000"
          iyy="0.6"  iyz="0.000000"
          izz="0.4"/>
      </inertial>

     <visual>
      <origin xyz="0 0 0" rpy="0 ${PI/2} 0"/>
        <geometry>
          <mesh filename="package://weichai_sim/meshes/ford_escape_wheel.dae"/>
          <scale xyz="1.2 1 1"/>
        </geometry>
      </visual>

      <collision>
        <origin xyz="0 0 0" rpy="0 ${PI} 0"/>
        <geometry>
         <cylinder length="${tyre_length}" radius="${tyre_radius}"/>
        </geometry>
     </collision>
</link>

<!--Back Left Wheel-->
<link name="back_left_wheel_link">
      <inertial>
        <origin xyz="0 0 0" rpy="0 ${-PI} 0"/>
        <mass value="10.00"/>
        <inertia
          ixx="0.4"  ixy="0.000000"  ixz="0.000000"
          iyy="0.6"  iyz="0.000000"
          izz="0.4"/>
      </inertial>

     <visual>
        <origin xyz="0 0 0" rpy="0 ${PI/2} 0"/>
        <geometry>
          <mesh filename="package://weichai_sim/meshes/ford_escape_wheel.dae"/>
          <scale xyz="1.2 1 1"/>
        </geometry>
      </visual>

      <collision>
        <origin xyz="0 0 0" rpy="0 ${-PI} 0"/>
        <geometry>
         <cylinder length="${tyre_length}" radius="${tyre_radius}"/>
        </geometry>
     </collision>
</link>

<joint name="front_right_steering_joint" type="revolute">
	<parent link="base_link"/>
	<child link="front_right_steering_link"/>
	<origin xyz="${wheelbase} ${-tyre_y} 0" rpy="0 0 0"/>
  <axis xyz="0 0 1"/>
	<limit effort="1000.0" lower="${-str_angle}" upper="${str_angle}" velocity="0.5"/>
</joint>

<joint name="front_left_steering_joint" type="revolute">
  <parent link="base_link"/>
  <child link="front_left_steering_link"/>
  <origin xyz="${wheelbase} ${tyre_y} 0" rpy="0 0 0"/>
  <axis xyz="0 0 1"/>
  <limit effort="1000.0" lower="${-str_angle}" upper="${str_angle}" velocity="0.5"/>
</joint>

<joint name="front_left_wheel_joint" type="continuous">
      <parent link="front_left_steering_link"/>
      <child link="front_left_wheel_link"/>
      <origin xyz="0 0 0" rpy="${PI/2} 0 ${-PI}"/>
      <axis xyz="0 0 1"/>
      <limit effort="0.0" velocity="100.0" />
</joint>

<joint name="front_right_wheel_joint" type="continuous">
      <parent link="front_right_steering_link"/>
      <child link="front_right_wheel_link"/>
      <origin xyz="0 0 0" rpy="${PI/2} 0 ${-PI}"/>
      <axis xyz="0 0 1"/>
      <limit effort="0.0" velocity="100.0" />
</joint>

<joint name="back_right_wheel_joint" type="continuous">
      <parent link="base_link"/>
      <child link="back_right_wheel_link"/>
      <origin xyz="0 ${-tyre_y} 0" rpy="${PI/2} 0 ${-PI}"/>
      <axis xyz="0 0 1"/>
      <dynamics damping="0.1"/>
      <limit effort="10000" velocity="100" />
      <joint_properties damping="0.0" friction="5.0" />
</joint>

<joint name="back_left_wheel_joint" type="continuous">
      <parent link="base_link"/>
      <child link="back_left_wheel_link"/>
      <origin xyz="0 ${tyre_y} 0" rpy="${PI/2} 0 ${-PI}"/>
      <axis xyz="0 0 1"/>
      <dynamics damping="0.1"/>
      <limit effort="10000" velocity="100" />
      <joint_properties damping="0.0" friction="5.0" />
</joint>

<!-- camera -->
<xacro:include filename="$(find weichai_sim)/urdf/vehicle_sensors.urdf.xacro" />
<xacro:front_camera name="front_camera_long" parent_link="base_link" x="3.2" y="0.0" z="1.6" roll="0" pitch="0.0" yaw="0" horizontal_fov="1.0471975511965976" image_width="1384" image_height="1024" />
<xacro:front_camera name="front_camera_short" parent_link="base_link" x="3.2" y="0.2" z="1.6" roll="0" pitch="0.0" yaw="0" horizontal_fov="2.0943951023931953" image_width="1384" image_height="1024" />
<xacro:fisheye_camera name="left_fisheye" parent_link="base_link" x="3.38" y="1.0" z="1.05" roll="0" pitch="0.3" yaw="0.7853981633974483" horizontal_fov="3.31" image_width="1384" image_height="1024"/>
<xacro:fisheye_camera name="right_fisheye" parent_link="base_link" x="3.38" y="-1.0" z="1.05" roll="0" pitch="0.3" yaw="-0.7853981633974483" horizontal_fov="3.31" image_width="1384" image_height="1024" />
<xacro:fisheye_camera name="front_fisheye" parent_link="base_link" x="4.7" y="0.0" z="0.4" roll="0" pitch="0.0" yaw="0.0" horizontal_fov="6.283" image_width="320" image_height="240"/>
<xacro:fisheye_camera name="back_fisheye" parent_link="base_link" x="-1.3" y="0.0" z="0.18" roll="0" pitch="0.3" yaw="-3.14" horizontal_fov="3.31" image_width="1384" image_height="1024" />

<!--GPS antennas-->
<xacro:gps_antenna name="front_antenna" parent_link="base_link" x="2.2" y="0" z="2.28"/>
<xacro:gps_antenna name="back_antenna" parent_link="base_link" x="-0.5" y="0" z="2.28"/>

<!--GPS-->
<xacro:vehicle_gps name="perfect_gps" parent_link="base_link" x="0" y="-0.2" z="0.6" rate="50.0" ref_lat="45.0" ref_lon="-81.0" />

<!-- velodyne -->
<xacro:include filename="$(find velodyne_description)/urdf/HDL-32E.urdf.xacro"/>
<HDL-32E parent="base_link" name="HDL32_fl" topic="/lidar/hdl32_fl/PointCloud2" hz="20" samples="440">
  <origin xyz="3.5 0.95 1.4" rpy="0 0 0" />
</HDL-32E>

<xacro:include filename="$(find velodyne_description)/urdf/HDL-32E.urdf.xacro"/>
<HDL-32E parent="base_link" name="HDL32_fr" topic="/lidar/hdl32_fr/PointCloud2" hz="20" samples="440">
  <origin xyz="3.5 -0.95 1.4" rpy="0 0 0" />
</HDL-32E>

<xacro:include filename="$(find velodyne_description)/urdf/VLP-16.urdf.xacro"/>
<VLP-16 parent="base_link" name="VLP16_bl" topic="/lidar/vlp16_bl/PointCloud2" hz="10" samples="440"  collision_range="0.9" min_range="0.9" max_range="130.0">
  <origin xyz="-1.1 0.9 0.25" rpy="0 0 0" />
</VLP-16>

<xacro:include filename="$(find velodyne_description)/urdf/VLP-16.urdf.xacro"/>
<VLP-16 parent="base_link" name="VLP16_br" topic="/lidar/vlp16_br/PointCloud2" hz="10" samples="440"  collision_range="0.9" min_range="0.9" max_range="130.0">
  <origin xyz="-1.1 -0.9 0.25" rpy="0 0 0" />
</VLP-16>

<xacro:include filename="$(find velodyne_description)/urdf/VLP-16.urdf.xacro"/>
<VLP-16 parent="base_link" name="VLP16_fr" topic="/lidar/vlp16_fr/PointCloud2" hz="10" samples="440"  collision_range="0.9" min_range="0.9" max_range="130.0">
  <origin xyz="4.46 -0.86 0.25" rpy="0 0 0" />
</VLP-16>

<xacro:include filename="$(find velodyne_description)/urdf/VLP-16.urdf.xacro"/>
<VLP-16 parent="base_link" name="VLP16_fl" topic="/lidar/vlp16_fl/PointCloud2" hz="10" samples="440"  collision_range="0.9" min_range="0.9" max_range="130.0">
    <origin xyz="4.46 0.86 0.25" rpy="0 0 0" />
</VLP-16>

<!-- imu -->
<xacro:include filename="$(find weichai_sim)/urdf/vehicle_imu.xacro"/>
<xacro:vehicle_imu name="vehicle_imu" parent_link="base_link" x="0" y="0.0" z="0.6" />



<!--IBEO Scala-->
<!--<xacro:ibeo_lidar name="front_ibeo" parent_link="base_link" x="4.64" y="0.0" z="0.165" roll="0" pitch="0.0" yaw="0.0" />
<xacro:include filename="$(find ibeo_description)/urdf/IBEO-Scala-B3.urdf.xacro"/>
<IBEO-4 parent="base_link" name="ibeo" topic="/ibeo_points" hz="25" samples="1440">
  <origin xyz="4.68 0 0.165" rpy="0 0 0" />
</IBEO-4>-->




<!-- motors and transmissions for the two rear wheels -->

  <transmission name="tran1">
    <type>transmission_interface/SimpleTransmission</type>
    <joint name="back_right_wheel_joint">
      <hardwareInterface>VelocityJointInterface</hardwareInterface>
    </joint>
    <actuator name="motor1">
      <hardwareInterface>VelocityJointInterface</hardwareInterface>
      <mechanicalReduction>1</mechanicalReduction>
    </actuator>
  </transmission>

  <transmission name="tran2">
    <type>transmission_interface/SimpleTransmission</type>
    <joint name="back_left_wheel_joint">
      <hardwareInterface>VelocityJointInterface</hardwareInterface>
    </joint>
    <actuator name="motor2">
      <hardwareInterface>VelocityJointInterface</hardwareInterface>
      <mechanicalReduction>1</mechanicalReduction>
    </actuator>
  </transmission>

  <transmission name="rack_and_pinion_left">
    <type>transmission_interface/SimpleTransmission</type>
    <joint name="front_left_steering_joint">
      <hardwareInterface>PositionJointInterface</hardwareInterface>
    </joint>
    <actuator name="eps_left">
      <hardwareInterface>PositionJointInterface</hardwareInterface>
      <mechanicalReduction>1</mechanicalReduction>
    </actuator>
  </transmission>

  <transmission name="rack_and_pinion_right">
    <type>transmission_interface/SimpleTransmission</type>
    <joint name="front_right_steering_joint">
      <hardwareInterface>PositionJointInterface</hardwareInterface>
    </joint>
    <actuator name="eps_right">
      <hardwareInterface>PositionJointInterface</hardwareInterface>
      <mechanicalReduction>1</mechanicalReduction>
    </actuator>
  </transmission>

</robot>
